[package]
name = "volta"
version = "0.7.2"
authors = ["David Herman <david.herman@gmail.com>"]
license = "BSD-2-Clause"
repository = "https://github.com/volta-cli/volta"
edition = "2018"

[features]
cross-platform-docs = ["volta-core/cross-platform-docs"]
mock-network = ["mockito", "volta-core/mock-network"]
volta-dev = []
smoke-tests = []

[[bin]]
name = "volta-shim"
path = "src/volta-shim.rs"

[[bin]]
name = "volta-migrate"
path = "src/volta-migrate.rs"

[dependencies]
atty = "0.2"
volta-core = { path = "crates/volta-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.37"
console = "0.6.1"
failure_derive = "0.1.1"
failure = "0.1.1"
lazy_static = "1.3.0"
log = { version = "0.4", features = ["std"] }
volta-fail = { path = "crates/volta-fail" }
volta-fail-derive = { path = "crates/volta-fail-derive" }
validate-npm-package-name = { path = "crates/validate-npm-package-name" }
reqwest = { version = "0.9.9", features = ["hyper-011"] }
semver = { git = "https://github.com/mikrostew/semver", branch = "new-parser" }
structopt = "0.2.14"
rand = "0.5"
cfg-if = "0.1"
mockito = { version = "0.14.0", optional = true }
test-support = { path = "crates/test-support" }
textwrap = "0.11.0"
which = "2.0.1"
dirs = "1.0.4"
volta-migrate = { path = "crates/volta-migrate" }

[target.'cfg(windows)'.dependencies]
winreg = "0.6.0"

[dev-dependencies]
hamcrest2 = "0.3.0"
envoy = "0.1.3"

[workspace]
