[package]
name = "volta"
version = "0.5.3"
authors = ["David Herman <david.herman@gmail.com>"]
license = "BSD-2-Clause"
repository = "https://github.com/volta-cli/volta"
edition = "2018"

[features]
cross-platform-docs = ["volta-core/cross-platform-docs"]
mock-network = ["mockito", "volta-core/mock-network"]
volta-dev = []
smoke-tests = []

[[bin]]
name = "shim"
path = "src/shim.rs"

[dependencies]
volta-core = { path = "crates/volta-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.37"
console = "0.6.1"
failure_derive = "0.1.1"
failure = "0.1.1"
volta-fail = { path = "crates/volta-fail" }
volta-fail-derive = { path = "crates/volta-fail-derive" }
validate-npm-package-name = { path = "crates/validate-npm-package-name" }
reqwest = { version = "0.9.9", features = ["hyper-011"] }
semver = "0.9.0"
structopt = "0.2.14"
rand = "0.5"
cfg-if = "0.1"
mockito = { version = "0.14.0", optional = true }
test-support = { path = "crates/test-support" }
which = "2.0.1"

[dev-dependencies]
hamcrest2 = "0.2.3"
envoy = "0.1.3"

[workspace]
