[package]
name = "notion"
version = "0.1.5"
authors = ["David Herman <david.herman@gmail.com>"]
license = "BSD-2-Clause"
repository = "https://github.com/notion-cli/notion"

[features]
universal-docs = ["notion-core/universal-docs"]
mock-network = ["mockito", "notion-core/mock-network"]
notion-dev = []
smoke-tests = []

[[bin]]
name = "notion"
path = "src/notion.rs"

[[bin]]
name = "node"
path = "src/node.rs"

[[bin]]
name = "npm"
path = "src/npm.rs"

[[bin]]
name = "npx"
path = "src/npx.rs"

[[bin]]
name = "yarn"
path = "src/yarn.rs"

[[bin]]
name = "launchbin"
path = "src/launchbin.rs"

[[bin]]
name = "launchscript"
path = "src/launchscript.rs"

[dependencies]
docopt = "0.8"
notion-core = { path = "crates/notion-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.37"
console = "0.6.1"
failure_derive = "0.1.1"
failure = "0.1.1"
notion-fail = { path = "crates/notion-fail" }
notion-fail-derive = { path = "crates/notion-fail-derive" }
reqwest = "0.8.5"
semver = "0.9.0"
result = "1.0.0"
rand = "0.5"
cfg-if = "0.1"
mockito = { version = "0.14.0", optional = true }
test-support = { path = "crates/test-support" }

[dev-dependencies]
hamcrest2 = "0.2.3"
envoy = "0.1.3"

[workspace]
