[package]
name = "volta-migrate"
version = "0.1.0"
authors = ["Charles Pierce <cpierce.grad@gmail.com>"]
edition = "2018"

[dependencies]
volta-core = { path = "../volta-core" }
volta-layout = { path = "../volta-layout" }
log = { version = "0.4", features = ["std"] }
tempfile = "3.3.0"
semver = { git = "https://github.com/mikrostew/semver", branch = "new-parser" }
serde_json = { version = "1.0.89", features = ["preserve_order"] }
serde = { version = "1.0.149", features = ["derive"] }
walkdir = "2.3.2"
