[package]
name = "volta-core"
version = "0.1.0"
authors = ["David Herman <david.herman@gmail.com>"]
edition = "2018"

[features]
mock-network = ["mockito"]
# The `cross-platform-docs` feature flag is used for generating API docs for
# multiple platforms in one build.
# See ci/publish-docs.yml for an example of how it's enabled.
# See volta-core::path for an example of where it's used.
cross-platform-docs = []

[dependencies]
term_size = "0.3.0"
indicatif = "0.12.0"
console = ">=0.11.3, <1.0.0"
readext = "0.1.0"
serde_json = { version = "1.0.37", features = ["preserve_order"] }
serde = { version = "1.0.85", features = ["derive"] }
archive = { path = "../archive" }
lazycell = "1.2.0"
lazy_static = "1.3.0"
semver = { git = "https://github.com/mikrostew/semver", branch = "new-parser" }
cmdline_words_parser = "0.0.2"
fs-utils = { path = "../fs-utils" }
cfg-if = "1.0"
winfolder = "0.1"
tempfile = "3.0.2"
os_info = "1.1.0"
detect-indent = { git = "https://github.com/stefanpenner/detect-indent-rs", branch = "master" }
envoy = "0.1.3"
mockito = { version = "0.30.0", optional = true }
regex = "1.0.6"
dirs = "1.0.4"
sha-1 = "0.8.1"
hex = "0.3.2"
chrono = "0.4.6"
validate-npm-package-name = { path = "../validate-npm-package-name" }
textwrap = "0.11.0"
atty = "0.2"
log = { version = "0.4", features = ["std"] }
ctrlc = "3.1.3"
walkdir = "2.2.9"
volta-layout = { path = "../volta-layout" }
double-checked-cell = "2.1.0"
dunce = "1.0.0"
ci_info = "0.10.0"
hyperx = "1.0.0"
attohttpc = { version = "0.16.0", features = ["json"] }
chain-map = "0.1.0"
indexmap = "1.3.2"
retry = "1.0.0"
fs2 = "0.4.3"

[target.'cfg(windows)'.dependencies]
winreg = "0.10.1"
