[package]
name = "test-support"
version = "0.1.0"
authors = ["David Herman <david.herman@gmail.com>"]
edition = "2021"

[dependencies]
hamcrest2 = "0.3.0"
serde_json = { version = "1.0.132" }
thiserror = "2.0.3"
