[package]
name = "test-support"
version = "0.1.0"
authors = ["David Herman <david.herman@gmail.com>"]
edition = "2018"

[dependencies]
hamcrest2 = "0.3.0"
archive = { path = "../archive" }
serde_json = { version = "1.0.78" }
thiserror = "1.0.30"
