on:
  push:
    branches:
      - main

name: API Docs

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up cargo
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63
          override: true
      - name: Cargo Cache
        uses: Swatinem/rust-cache@v2
      - name: Build docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --features cross-platform-docs --no-deps --document-private-items
      - name: Prepare docs for publication
        run: |
          mkdir -p publish
          mv target/doc publish/main
          echo '<!doctype html><a href="volta">volta</a>' > publish/main/index.html
          echo '<!doctype html><a href="main">main</a>' > publish/index.html
      - name: Publish docs to GitHub pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          COMMIT_MESSAGE: Publishing GitHub Pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: publish
          SINGLE_COMMIT: true
